version: '3'

services:
  reverse-proxy:
    image: nginx:latest
    #image: reverse-proxy2:latest
    ports:
      - "80:80"
    volumes:
      - ./conf:/etc/nginx/conf.d
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
